name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/FUNDING.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/winget.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/FUNDING.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/winget.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [win-x64, win-arm64, linux-x64, linux-arm64, linux-musl-x64, linux-musl-arm64, osx-x64, osx-arm64]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: '9.x'

      - name: Restore (${{ matrix.rid }})
        run: dotnet restore mdr.csproj --runtime ${{ matrix.rid }}

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish (${{ matrix.rid }})
        run: |
          dotnet publish mdr.csproj \
            --configuration Release \
            --runtime ${{ matrix.rid }} \
            --self-contained \
            --no-restore
