name: Publish winget

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  winget:
    runs-on: windows-latest
    steps:
      - name: Submit to winget
        uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: michaelsanford.mdr
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
